# Generated by Django 3.2.3 on 2021-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=200)),
                ('bad_comments', models.JSONField(default='{}')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
