# Generated by Django 3.2.3 on 2021-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_data_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bad_comments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='data',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
